### ISSUE TITLE
FR: Display or open compare URL between ahead-branch & origin:master

### ISSUE THREAD

**Issue by katrinleinweber** [mewmew/guldkorn#1]
Thanks for publishing this tool :-)

I worked on [something similar in p(y)arallel](https://github.com/katrinleinweber/poPR). What do you think about not just displaying "status" and basic info about the fork, but opening GitHub's own compare-URL in the browser itself to review the changes?

Would that be a useful addition for guldkorn?

**Comment by mewmew** [comment]
Hi Katrin!

> Thanks for publishing this tool :-)

You are most welcome :) Also sweet to see you releasing a similar tool!

> I worked on something similar in p(y)arallel. What do you think about not just displaying "status" and basic info about the fork, but launching the compare-URL on GitHub itself to review the changes?
>
> Would that be a useful addition for guldkorn?

I think it's useful to present the compare link to the user. Do you have an example link that does the comparison between two repos (and two branches)?

I'm definitely fine with displaying the URL for comparing head and base. As users of `guldkorn` may have different browsers, or different use cases in mind than opening the links, I think it's fine to simply output it to terminal. Anyone who then wishes to open those links in the browser can just pipe it to another script which does just that.

If the output is expected to be consumed by other tools, we may also wish to add a `-json` flag to output the results in JSON format.

Cheers,
Robin

**Comment by katrinleinweber** [comment]
> […] example link that does the comparison between two repos (and two branches)?

https://github.com/mewmew/guldkorn/compare/master...katrinleinweber:demo-compare-urls So meta ;-D

> [...] it's fine to simply output it to terminal. Anyone who then wishes to open those links in the browser can just pipe it

Good point! In that respect, my tool indeed doesn't comply with UNIX philosophy...

**Comment by mewmew** [comment]
Thanks Katrin for the example link. Gotta love meta :)

I've implemented your suggestion in f1336f5b42ffef197d470866c41e21a62ecf83fe.

Cheers,
Robin

**Comment by katrinleinweber** [comment]
Awesome, thank you :-) So convenient to be able to just cmd-click on guldkorn's output now in iTerm!
